##
# Docker Drupal Development
#
# Main Docker Composer file
version: '2'

services:

  # Drupal web server
  web:
    image: dockerdrupaldev/apache2-php5:latest
    hostname: drupal
    links:
      - db:mysql
      - mailcatcher
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./sites:/var/www
      - apache_logs:/var/log/apache2
      - ./etc/PHP/docker.ini:/etc/php/5.6/conf.d/docker.ini

  # Database server
  db:
    build: images/mysql
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql

  # Email catcher
  mailcatcher:
    image: schickling/mailcatcher
    hostname: mailcatcher
    ports:
      - "1025:1025"
      - "8081:1080"

  # Web development tools
  web_tools:
    build: images/web_tools
    hostname: web-tools
    links:
      - db:mysql
      - mailcatcher
    ports:
      - "8080:80"
    volumes:
      - apache_logs:/var/log/apache2

  # CLI development tools with SSH
  cli_tools:
    image: dockerdrupaldev/cli-tools-php5:latest
    hostname: cli-tools
    links:
      - db:mysql
      - mailcatcher
    ports:
      - "2222:22"
    volumes:
      - ./databases:/docker/databases
      - ./sites:/docker/sites
      - ./sites:/var/www
      - /home/docker
      - apache_logs:/var/log/apache2

volumes:
  apache_logs: {}
  mysql: {}
