web:
  build: containers/drupal
  hostname: drupal
  links:
    - db:mysql
    - mailcatcher
    - solr
  ports:
    - "80:80"
  volumes:
    - ./sites/${SITE}:/var/www/

db:
  build: containers/mysql
  hostname: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root
  ports:
    - "3306:3306"
  volumes:
    - /var/lib/mysql  

adminer:
  image: clue/adminer
  hostname: adminer
  links:
    - db:mysql
  ports:
    - "8081:80"

mailcatcher:
  image: schickling/mailcatcher
  hostname: mailcatcher
  ports:
    - "1025:1025"
    - "8082:1080"

dev_tools:
  build: containers/dev_tools
  hostname: dev-tools
  links:
    - db:mysql
    - mailcatcher
    - web
  ports:
    - "2222:22"
  volumes:
    - /home/docker
    - ./databases:/docker/databases
    - ./sites:/docker/sites
    - ./sites/${SITE}:/var/www/

solr:
  image: solr
  hostname: solr
  ports: 
    - "8983:8983"
  volumes:
    - ./solr/${SITE}:/opt/solr/server/solr/drupal
