##
# Docker Drupal Development
#
# Elasticsearch override file
version: '2'

services:
  # Add link to Drupal web server
  web:
    links:
      - elasticsearch

  # Elasticsearch server
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
    hostname: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

  # Kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:5.2.2
    hostname: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  elasticsearch: {}
