##
# Docker Drupal Development
#
# Main Docker Composer file
version: '2'

services:

  # Drupal web server with PHP 7
  web:
    image: dockerdrupaldev/apache2-php7:latest
    volumes:
      - ./etc/php/docker.ini:/etc/php/7.0/conf.d/docker.ini

  # CLI development tools with SSH and PHP 7
  cli_tools:
    image: dockerdrupaldev/cli-tools-php7:latest
