##
# Docker Drupal Development
#
# Redis override file

# Override Drupal web server
version: '2'

services:

  web:
    links:
      - redis

  # Redis server
  redis:
    image: redis:latest
    ports:
      - "6379"
