##
# Docker Drupal Development
#
# Vanrish override file
version: '2'

services:

  # Varnish server
  varnish:
    image: dockerdrupaldev/varnish:latest
    hostname: varnish
    ports:
      - "81:80"
      - "6082:6082"
    links:
      - web
    volumes:
      - ./etc/varnish:/etc/varnish
